package com.example.lzl.java.jinjieniuke.lfutest;

public class test {
    public static void main(String[] args){

//        ["LFUCache",,"put","put","put","get","put","get","get","put","put","get","put","put","put","put","get","put","put","get","put","put","get","put","put","put","put","put","get","put","put","get","put","get","get","get","put","get","get","put","put","put","put","get","put","put","put","put","get","get","get","put","put","put","get","put","put","put","get","put","put","put","get","get","get","put","put","put","put","get","put","put","put","put","put","put","put"]
//[[],[],[],[],[],[],[],[],[12,17],[9,1],[6,19],[4],[5],[5],[8,1],[11,7],[5,2],[9,28],[1],[2,2],[7,4],[4,22],[7,24],[9,26],[13,28],[11,26]]
        LFUCache cache = new LFUCache(10);
        cache.put(10,13);
        cache.put(3,17);
        cache.put(6,11);
        cache.put(10,5);
        cache.put(9,10);
        System.out.println(cache.get(13));
        cache.put(2,19);
        System.out.println(cache.get(2));
        System.out.println(cache.get(3));
        cache.put(5,25);
        System.out.println(cache.get(8));
        cache.put(9,22);
        cache.put(5,5);
        cache.put(1,30);
        System.out.println(cache.get(11));
        cache.put(9,12);
        System.out.println(cache.get(7));
        System.out.println(cache.get(5));
        System.out.println(cache.get(8));
        System.out.println(cache.get(9));
        cache.put(4,30);
        cache.put(9,3);
        System.out.println(cache.get(9));
        System.out.println(cache.get(10));
        System.out.println(cache.get(10));
        System.out.println("===========================");
        cache.put(6,14);
        cache.put(3,1);
        System.out.println(cache.get(3));
        cache.put(10,11);
        System.out.println(cache.get(8));
        cache.put(2,14);
        System.out.println(cache.get(1));
        System.out.println(cache.get(5));
        System.out.println(cache.get(4));
        cache.put(11,4);
        cache.put(12,24);
        cache.put(5,18);
        System.out.println(cache.get(13));
        cache.put(7,23);
        System.out.println(cache.get(8));
        System.out.println(cache.get(12));
        cache.put(3,27);
        cache.put(2,12);
        System.out.println(cache.get(5));
        cache.put(2,9);
        cache.put(13,4);
        cache.put(8,18);
        cache.put(1,7);
        System.out.println(cache.get(6));
        cache.put(9,29);
        cache.put(8,21);
        System.out.println(cache.get(5));

        cache.put(6,30);
        cache.put(1,12);
        System.out.println(cache.get(10));
        cache.put(4,15);
        cache.put(7,22);
        cache.put(11,26);
        cache.put(8,17);
        cache.put(9,29);
        System.out.println(cache.get(5));
        cache.put(3,4);
        cache.put(11,30);
        System.out.println(cache.get(12));
        cache.put(4,29);
        System.out.println(cache.get(3));
        System.out.println(cache.get(9));
        System.out.println(cache.get(6));
        cache.put(3,4);
        System.out.println(cache.get(1));
        System.out.println(cache.get(10));
        cache.put(3,29);
        cache.put(10,28);
        cache.put(1,20);
        cache.put(11,13);
//        System.out.println(cache.get(3));
//        cache.put(3,12);
//        cache.put(3,8);
//        cache.put(10,9);
//        cache.put(3,26);
//        System.out.println(cache.get(8));
//        System.out.println(cache.get(7));
//        System.out.println(cache.get(5));
//        cache.put(13,17);
//        cache.put(2,27);
//        cache.put(11,15);
//        System.out.println(cache.get(12));
//        cache.put(9,19);
//        cache.put(2,15);
//        cache.put(3,16);
//        System.out.println(cache.get(1));
    }
}
